@extends('layouts.app')

@section('title', 'Agentic AI K3 | Portal ITS')

@section('content')
<section class="agent-hero py-5"><div class="container py-lg-4"><div class="row align-items-end g-4"><div class="col-lg-9"><span class="eyebrow light"><i class="bi bi-cpu me-1"></i> PLATFORM AGENTIC AI</span><h1 class="display-5 fw-bold mt-3 mb-3">Sistem Agentic AI Berbasis MCP Server untuk Verifikasi Kepatuhan SOP Keselamatan (K3) Laboratorium.</h1><p class="lead mb-0 opacity-75">Dari otomasi yang kaku menuju agen otonom yang memahami konteks dan menjaga keamanan.</p></div><div class="col-lg-3"><div class="theme-chip"><span>Tema agent</span><strong>{{ $tema }}</strong></div></div></div></div></section>
<section class="container py-5"><div class="row g-5"><div class="col-lg-5"><span class="eyebrow">WHY THIS PROJECT</span><h2 class="h2 fw-bold mt-2">AI yang memahami maksud, bukan sekadar formulir.</h2><p class="text-secondary">Proyek ini mendemonstrasikan transisi dari <em>Otomasi Tradisional yang kaku</em> menjadi <em>Agentic AI yang otonom</em>. LLM membedah niat pengguna dari bahasa natural, lalu memanggil tools melalui MCP Server untuk mengecek database kampus.</p><p class="text-secondary mb-0">Sistem menangani edge-case keamanan seperti <em>identity spoofing</em> tanpa mengekspos akses database langsung ke AI.</p></div><div class="col-lg-7"><span class="eyebrow">CORE CAPABILITIES</span><div class="feature-list mt-3"><div class="feature-item"><span class="feature-number">01</span><div><h3 class="h5">Natural Language Translation</h3><p class="text-secondary small mb-0">Menerjemahkan “alat peleleh timah” menjadi query resmi “Solder 40W”.</p></div></div><div class="feature-item"><span class="feature-number">02</span><div><h3 class="h5">Autonomous Rule Verification</h3><p class="text-secondary small mb-0">Mengambil SOP Lab dan status kelulusan K3 melalui MCP Server untuk mencocokkan kelayakan.</p></div></div><div class="feature-item"><span class="feature-number">03</span><div><h3 class="h5">Contextual Problem Solving</h3><p class="text-secondary small mb-0">Menawarkan solusi prosedural, seperti peminjaman dengan pendampingan Asisten Lab.</p></div></div><div class="feature-item"><span class="feature-number">04</span><div><h3 class="h5">Anti-Spoofing Verification (OTP)</h3><p class="text-secondary small mb-0">Memicu OTP ke email resmi kampus berdasarkan NRP untuk alat berisiko tinggi.</p></div></div></div></div></div></section>
<section class="container pb-5"><div class="cta-panel p-4 p-lg-5 d-flex flex-column flex-md-row align-items-md-center justify-content-between gap-3"><div><h2 class="h4 mb-1">Siap menjelajah lebih jauh?</h2><p class="text-secondary mb-0">Kembali ke portal atau cek profil mahasiswa.</p></div><div class="d-flex gap-2"><a class="btn btn-dark" href="{{ route('home') }}">Beranda</a><a class="btn btn-outline-dark" href="{{ route('dashboard.mahasiswa', '5025211001') }}">Profil</a></div></div></section>
@endsection
